# Generated by Django 5.0.7 on 2024-08-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('places', models.TextField(max_length=200)),
                ('duration', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('services_included', models.TextField(max_length=300)),
                ('services_excluded', models.TextField(max_length=300)),
                ('stock', models.IntegerField()),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
